---
- name: Set TestPMD Command If Not Defined
  set_fact:
    testpmd_cmd: |
      {{ testpmd_bin }} -l {{ testpmd_lcores }} \
      -n {{ testpmd_mem_channels}} \
      --socket-mem {{ testpmd_socket_mem }} -- -i \
      --nb-cores={{ testpmd_forward_cores }} \
      --forward-mode=rxonly \
      --eth-peer=0,{{ trex_macs.split(',')[0] }} \
      --eth-peer=1,{{ trex_macs.split(',')[1] }} \
      --rxd={{ testpmd_rxd }} \
      --txd={{ testpmd_txd }} \
      --rxq={{ testpmd_rxq }} \
      --txq={{ testpmd_txq }} \
      --cmdline-file=/tmp/cmdline &>/tmp/testpmddef.log
  when: testpmd_cmd is not defined

- name: Log testpmd Command
  debug:
    var: testpmd_cmd

- name: Run testpmd In Dettached Tmux Session
  shell: |
    tmux new -d -s testpmd
    tmux send-keys -t testpmd "{{ testpmd_cmd }}" ENTER
    tmux send-keys -t testpmd "show port stats all" ENTER
  become: True

- name: Pause And Let TestPMD Run
  pause:
    seconds: 10

- name: Query If TestPMD Aborted
  slurp:
    src: '/tmp/testpmd.log'
  register: testpmd_log_output

- name: Print TestPMD Error
  fail:
    msg: "{{ testpmd_log_output['content'] | b64decode }}"
  failed_when: "'PANIC' in testpmd_log_output['content'] | b64decode"
